name: API Tests

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Download code
              uses: actions/checkout@v3

              # Cache Yarn dependencies
            - name: Cache Yarn dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      ~/.cache/yarn
                  key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }} # Cache key based on yarn.lock hash
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Setup Nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: yarn install

            - name: Run tests
              run: yarn test
